hook.Add("PlayerSpawning", "PlayerSpawning", function(ply, stats)
    ply:CreateInventory({}, 24)
    ply:RegisterPlayer("models/player/darky_m/rust/hazmat.mdl")
    ply:SetHunger(math.random(80,120))
	ply:SetThirst(math.random(80,120))
end)